version: "3.8"
services:
  pedidos:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8002:8000
    depends_on:
      - pedidos_db

  pedidos_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: pedidos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33067:3306
