version: "3.8"
services:
  produtos:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8003:8000
    depends_on:
      - produtos_db

  produtos_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: produtos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306
